spring:
  application:
    name: alumnos-api
  datasource:
    # PostgreSQL Configuration
    url: jdbc:postgresql://localhost:5432/db-alumnos
    username: postgres
    password: GatoVolador2011#
    driver-class-name: org.postgresql.Driver
    # SQL Server Configuration
    # url: jdbc:sqlserver://localhost:1433;databaseName=universidad;encrypt=true;trustServerCertificate=true
    # username: sa
    # password: password
    # driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update # Use none in production, validate or update for development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public # For PostgreSQL, use your schema
        # default_schema: dbo # For SQL Server
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # database-platform: org.hibernate.dialect.SQLServer2012Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

